# These are supported funding model platforms

custom: ['https://axcora.my.id/pico/picobook/','https://www.hockeycomputindo.com/2010/12/blog-post.html','https://axcora.com/sourcecode/','https://axcora.com/getaxcoracms']
